spring.application.name=plantillas

# Verifica que el puerto 26853 sea el actual en tu consola de Aiven
spring.datasource.url=jdbc:mysql://mysql-222d0a84-luisdanieldelgado17.d.aivencloud.com:26853/fifa?createDatabaseIfNotExist=true&useSSL=true&allowPublicKeyRetrieval=true
spring.datasource.username=avnadmin
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
# Forzamos el dialecto para evitar el error de "Unable to determine Dialect"
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect